// app/layout.tsx

import { UserProvider } from '@auth0/nextjs-auth0/client';  // Correct import path

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Wrap the app with UserProvider to access Auth0 user data */}
        <UserProvider>
          {children}  {/* This ensures all children can access user context */}
        </UserProvider>
      </body>
    </html>
  )
}
