name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Build Docker image for Next.js application
      - name: Build Docker image for Next.js
        run: |
          docker build --no-cache -t referloop/referimage:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push referloop/referimage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the build job runs before deployment

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Deploy to EC2 and run Docker image locally with no cache
      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ubuntu
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOSTNAME << 'EOF'
            echo "Connected to EC2, pulling and running Docker image..."
            docker pull referloop/referimage:latest
            echo "Stopping existing container if it exists..."
            docker stop referLeap || true
            echo "Removing old container if it exists..."
            docker rm referLeap || true
            echo "Running new Docker container..."
            docker run -d -p 3000:3000 --name referLeap --restart unless-stopped referloop/referimage:latest
            echo "Deployment completed!"
          EOF
